schemas:
  base: 'http://www.hpi.uni-potsdam.de/semmul2014/merged/'
  lom: 'http://www.hpi.uni-potsdam.de/semmul2014/lodofmovies.owl#'
  schema: 'http://schema.org/'
  dbpedia: 'http://dbpedia.org/ontology/'
  rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
  rdfs: 'http://www.w3.org/2000/01/rdf-schema#'
  xsd: 'http://www.w3.org/2001/XMLSchema#'
graphs:
  mapped: 'http://example.com/mapped'
  merged: 'http://example.com/merged'
queues:
  mapping: 'lom.mapped'
  merging: 'lom.merged'
