weights:
  movie: # must sum up to 1
    title: 0.5
    director: 0.1
    release: 0.2
    actors: 0.2
  person: # must sum up to 1
    name_alias: 0.7
    birthdate: 0.3
  performance: # must sum up to 1
    character: 0.4
    actor: 0.6
  # organization: only name until now
  # director: same as person until now

thresholds:
  matching: 0.55
  person_equivalence: 0.8
  ff_lower_bound: 0.6

settings:
  date_std_dev_d: 90

control:
  enable_ff: false
  debug: false
  calculate_actors : false