schemas:
  # TODO insert missing namespaces (for several resources)
  base_tmdb: 'http://semmul2014.hpi.de/tmdb/'
  base: 'http://semmul2014.hpi.de/merged/'
  lom: 'http://semmul2014.hpi.de/lodofmovies.owl#'
  tmdb: 'http://semmul2014.hpi.de/themoviedb.owl#'
  schema: 'http://schema.org/'
  dbpedia: 'http://dbpedia.org/ontology/'
  dbprop: 'http://dbpedia.org/property/'
  rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
  rdfs: 'http://www.w3.org/2000/01/rdf-schema#'
  owl: 'http://www.w3.org/2002/07/owl#'
  foaf: 'http://xmlns.com/foaf/0.1/'
  xsd: 'http://www.w3.org/2001/XMLSchema#'
  pav_lastupdateon: 'http://purl.org/pav/lastUpdateOn'
  base_freebase: 'http://rdf.freebase.com/ns'

graphs:
  raw: 'http://semmul2014.hpi.de/graph/raw'
  mapped: 'http://semmul2014.hpi.de/graph/mapped'
  merged: 'http://semmul2014.hpi.de/graph/merged' # main

queues:
  # TODO insert queues for several resources
  source_tmdb: 'lom.source.tmdb.' # movie_id
  source_freebase: 'lom.source.freebase.' # movie_id
  raw_tmdb: 'lom.raw_db.tmdb.' # movie_uri
  raw_freebase: 'lom.raw_db.freebase.' # movie_uri
  raw_dbpedia: 'lom.raw_db.dbpedia.' #movie
  mapping: 'lom.mapped.' # movie_uri
  merging: 'lom.merged.' # movie_uri

# main types of entities for the matcher
types:
  movie_type: "http://schema.org/Movie"
  person_type: "http://schema.org/Person"
  organization_type: "http://schema.org/Organization"
  director_type: "http://semmul2014.hpi.de/lodofmovies.owl#Director"
  performance_type: "http://semmul2014.hpi.de/lodofmovies.owl#Performance"
